service: thomasforicher

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: prod

functions:
  hello:
    handler: handler.hello
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: /
          method: get
          cors: true
